name: markdown_editor
description: A TextField Widget that allow you to convert easily what's in the
  TextField to Markdown with custom toolbar support.
version: 0.2.6+1
homepage: https://github.com/OmkarDabade/markdown_editor
repository: https://github.com/OmkarDabade/markdown_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  expandable: ^5.0.1
  markdown: ^5.0.0
  flutter_markdown: ^0.6.10
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: null
